# Generated by Django 3.2.16 on 2022-10-25 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankRechargeRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='充值金额')),
                ('card_no', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='余额')),
            ],
        ),
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_number', models.CharField(max_length=18, verbose_name='身份证号码')),
                ('account', models.CharField(max_length=200, verbose_name='账号')),
                ('name', models.CharField(max_length=200, verbose_name='用户名')),
                ('sex', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('login_password', models.CharField(max_length=32)),
                ('pay_password', models.CharField(max_length=32)),
                ('qx', models.CharField(max_length=200)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='BuyStockRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='购买金额')),
                ('stock_number', models.CharField(max_length=200, verbose_name='股票编号，也就是股票代码')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='购买后，账户余额')),
            ],
        ),
        migrations.CreateModel(
            name='RechargePhoneBillRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('name', models.CharField(max_length=200, verbose_name='用户名')),
                ('pay_money', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='充值金额')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='余额')),
            ],
        ),
        migrations.CreateModel(
            name='TransferAccountsRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('payee_id', models.IntegerField(verbose_name='收款账户ID')),
                ('payee_name', models.CharField(max_length=200)),
                ('payee_phone', models.CharField(max_length=200)),
                ('money', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='转账金额')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='余额')),
            ],
        ),
        migrations.CreateModel(
            name='UserBankCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('card_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WithDrawalRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='提现金额')),
                ('card_no', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='余额')),
            ],
        ),
    ]
