# Generated by Django 3.2.16 on 2022-10-24 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_number', models.CharField(max_length=18)),
                ('account', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('login_password', models.CharField(max_length=32)),
                ('pay_password', models.CharField(max_length=32)),
                ('qx', models.CharField(max_length=200)),
                ('money', models.DecimalField(decimal_places=2, max_digits=12)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
