# Generated by Django 3.2.16 on 2022-10-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='account',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
