# Generated by Django 3.2.16 on 2022-10-26 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_userbankcard_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.CharField(max_length=200, verbose_name='账号')),
                ('password', models.CharField(max_length=32)),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
    ]
