# Generated by Django 3.2.16 on 2022-10-24 14:53

import bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_bankuser_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRechargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='充值金额')),
                ('card_no', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='余额')),
            ],
            bases=(models.Model, bank.models.BaseModelMinxin),
        ),
        migrations.CreateModel(
            name='BuyStockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='购买金额')),
                ('stock_number', models.CharField(max_length=200, verbose_name='股票编号，也就是股票代码')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='购买后，账户余额')),
            ],
            bases=(models.Model, bank.models.BaseModelMinxin),
        ),
        migrations.CreateModel(
            name='RechargePhoneBillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('name', models.CharField(max_length=200, verbose_name='用户名')),
                ('pay_money', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='充值金额')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='余额')),
            ],
            bases=(models.Model, bank.models.BaseModelMinxin),
        ),
        migrations.CreateModel(
            name='TransferAccountsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('payee_id', models.IntegerField(verbose_name='收款账户ID')),
                ('payee_name', models.CharField(max_length=200)),
                ('payee_phone', models.CharField(max_length=200)),
                ('money', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='转账金额')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='余额')),
            ],
            bases=(models.Model, bank.models.BaseModelMinxin),
        ),
        migrations.CreateModel(
            name='UserBankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('card_no', models.CharField(max_length=100)),
            ],
            bases=(models.Model, bank.models.BaseModelMinxin),
        ),
        migrations.CreateModel(
            name='WithDrawalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='提现金额')),
                ('card_no', models.CharField(max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='余额')),
            ],
            bases=(models.Model, bank.models.BaseModelMinxin),
        ),
        migrations.RemoveField(
            model_name='bankuser',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='bankuser',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='account',
            field=models.CharField(max_length=200, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='id_number',
            field=models.CharField(max_length=18, verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='name',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
    ]
