# Generated by Django 3.2.16 on 2022-10-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_manageruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='是否被封禁'),
        ),
    ]
