# Generated by Django 3.2.16 on 2022-10-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20221024_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
